import { Roboto } from 'next/font/google';

import 'app/sass/global.module.scss';
import { Header } from 'app/components/shared/Header';
import { Footer } from 'app/components/shared/Footer';

const roboto = Roboto({
  weight: ['100', '300', '500', '700'],
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: {
//     template: '%s | Future world',
//     default: 'Future world',
//   },
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
